version: '3'

includes:
    system: ./system
    app: ./app

tasks:
    setup:
        cmds:
            - task -d /ops/setup
            - task: system:setup
            - task: app:setup

    update:
        cmds:
            - task: git-fetch
            - task: setup
            - task: system:default
            - task: app:default

    git-fetch:
        cmds:
            - git fetch --depth=10
            - git gc --aggressive --prune=all
            - du -sh .git

    issue-cert:
        interactive: true
        cmds:
            - |
                docker run -it --rm \
                    --name certbot \
                    -v '/etc/letsencrypt:/etc/letsencrypt' \
                    certbot/certbot \
                        certonly \
                            --manual \
                            --domain shqld.dev \
                            --email me@shqld.dev \
                            --agree-tos \
                            --manual-public-ip-logging-ok \
                            --preferred-challenges dns
