version: '3'

includes:
    system: ./system
    monitoring: ./monitoring
    app: ./app

tasks:
    setup:
        cmds:
            - task -d /ops/setup
            - task: system:setup
            - task: monitoring:setup
            - task: app:setup

    update:
        cmds:
            - task: git-pull
            - task: setup
            - task: system:restart
            - task: app:update

    git-pull:
        preconditions:
            - sh: git diff --exit-code
              msg: Working tree is NOT clean
        cmds:
            - git pull --depth=10
            - git gc --aggressive --prune=all
            - du -sh .git

    install-newrelic:
        status:
            - cat $HOME/.newrelic/newrelic-cli.log | grep '^{' | jq -r 'select(.status == "INSTALLED").recipe_name' | grep -q infrastructure-agent-installer
        preconditions:
            - test -v NEW_RELIC_API_KEY
            - test -v NEW_RELIC_ACCOUNT_ID
        cmds:
            - curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash
            - /usr/local/bin/newrelic install -y

    issue-cert:
        interactive: true
        cmds:
            - |
                docker run -it --rm \
                    --name certbot \
                    -v '/etc/letsencrypt:/etc/letsencrypt' \
                    certbot/certbot \
                        certonly \
                            --manual \
                            --domain shqld.dev \
                            --email me@shqld.dev \
                            --agree-tos \
                            --manual-public-ip-logging-ok \
                            --preferred-challenges dns
