version: '3'

tasks:
    setup:
        cmds:
            - task -d /ops/setup

    issue-cert:
        interactive: true
        cmds:
            - |
                docker run -it --rm \
                    --name certbot \
                    -v '/etc/letsencrypt:/etc/letsencrypt' \
                    certbot/certbot \
                        certonly \
                            --manual \
                            --domain shqld.dev \
                            --email me@shqld.dev \
                            --agree-tos \
                            --manual-public-ip-logging-ok \
                            --preferred-challenges dns
