version: '3.8'
services:
    nginx:
        image: cdrocker/nginx:latest
        ports:
            - '8443:443/tcp'
            - '8443:443/udp'
        networks:
            - gateway
        volumes:
            - /ops/gateway/nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        user: '${CONTAINER_UID}'
        deploy:
            replicas: 1

networks:
    gateway:
        name: gateway
