#!/usr/bin/sh

echo "
# For replacing /ops

robot ALL=(root) NOPASSWD: $(which rm) -rf /ops
robot ALL=(root) NOPASSWD: $(which git) clone *

robot ALL=(root) NOPASSWD: $(which task) update -d /ops --silent
"