#!/bin/bash

set -eu

cd /ops

if grep ops < /etc/group; then
  echo "Skipping adding group(ops) ..."
else
  echo "Adding group(ops) ..."
  groupadd ops
fi

chown sho -R .
chgrp ops -R .
chmod g+rwx -R .
