#!/bin/bash

set -eu

cd /ops

echo "(add_user_robot) Starting ..."

if grep robot < /etc/group; then
  echo "Skipping adding user(robot) ..."
else
  echo "Adding user(robot) ..."
  useradd robot
fi

echo "Adding user(robot) to group(docker, ops) ..."
usermod -a -G docker robot
usermod -a -G ops robot

echo "Modifying sho's commands ..."
chmod +x src/commands/sho/*

if grep "robot ALL=(root)" < /etc/sudoers; then
  echo "Skipping adding robot to sudoers ..."
else
  echo "Adding permissions to user(robot) ..."
  for command in src/commands/sho/*; do
    echo "robot ALL=(ALL) NOPASSWD: /ops/src/commands/sho/$command" >> /etc/sudoers
  done
fi

echo "Setting ssh config ..."
if [ ! -d .ssh ]; then
  mkdir .ssh
  chmod 700 .ssh
fi
echo $AUTHORIZED_KEY_ROBOT > /home/robot/.ssh/authorized_keys
chmod 600 /home/robot/.ssh/authorized_keys
chown robot -R /home/robot/.ssh

echo "
Match User robot
  PasswordAuthentication no
  PubkeyAuthentication yes
  AuthorizedKeysFile /home/robot/.ssh/authorized_keys
" >> /etc/ssh/sshd_config

echo "(add_user_robot) Done"
