#! /bin/sh

set -eu

# https://manual.sakura.ad.jp/vps/network/ipv6/centos-stream-8.html

echo "Setting up IPv6 ..."

echo cat /etc/sysctl.conf
  cat /etc/sysctl.conf

sed -i -e "/net.ipv6.conf.all.disable_ipv6/s/1/0/" /etc/sysctl.conf
sed -i -e "/net.ipv6.conf.default.disable_ipv6/s/1/0/" /etc/sysctl.conf

echo cat /etc/sysctl.conf
  cat /etc/sysctl.conf

echo ip addr show ens3
  ip addr show ens3
echo cat /etc/sysconfig/network
  cat /etc/sysconfig/network
echo cat /etc/sysconfig/network-scripts/ifcfg-ens3
  cat /etc/sysconfig/network-scripts/ifcfg-ens3


sed -i -e "s/^#//g" /etc/sysconfig/network
sed -i -e "s/^#//g" /etc/sysconfig/network-scripts/ifcfg-ens3

echo cat /etc/sysconfig/network
cat /etc/sysconfig/network
echo cat /etc/sysconfig/network-scripts/ifcfg-ens3
cat /etc/sysconfig/network-scripts/ifcfg-ens3
