#! /bin/sh

set -eu

# -----------------------------------------------

echo "Installing docker ..."

yum install -y yum-utils 
yum-config-manager -y \
  --add-repo \
  https://download.docker.com/linux/centos/docker-ce.repo
yum -y remove podman # https://github.com/containers/podman/issues/4791
yum install -y docker-ce docker-ce-cli containerd.io

curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# -----------------------------------------------

echo "Enabling docker as daemon ..."
systemctl enable docker

echo "Starting docker ..."
systemctl start docker

echo "Starting docker swarm mode ..."
docker swarm init || echo "docker swarm has already been started"

# echo "Logging in to ghcr.io ..."
# echo $GITHUB_PACKAGE_SHQLD_TOKEN | docker login -u shqld --password-stdin ghcr.io
