version: '3.8'
services:
    nginx:
        image: ranadeeppolavarapu/nginx-http3
        ports:
            - target: 443
              published: 443
              protocol: tcp
            - target: 443
              published: 443
              protocol: udp
        volumes:
            - type: bind
              source: ./nginx/nginx.conf
              target: /etc/nginx/nginx.conf
              read_only: true
            - type: bind
              source: /var/log/nginx
              target: /var/log/nginx
            - type: bind
              source: /etc/letsencrypt/live/shqld.dev/fullchain.pem
              target: /etc/letsencrypt/live/shqld.dev/fullchain.pem
              read_only: true
            - type: bind
              source: /etc/letsencrypt/live/shqld.dev/privkey.pem
              target: /etc/letsencrypt/live/shqld.dev/privkey.pem
              read_only: true
        depends_on:
            - varnish
        restart: always

    varnish:
        image: ghcr.io/shqld/varnish:latest
        tmpfs: /var/lib/varnish:exec
        volumes:
            - type: bind
              source: ./varnish
              target: /etc/varnish
              read_only: true
            - type: bind
              source: /var/log/varnish
              target: /var/log/varnish
        depends_on:
            - dev
            - me
        restart: always

    bind:
        image: internetsystemsconsortium/bind9:9.18
        ports:
            - target: 53
              published: 53
              protocol: tcp
            - target: 53
              published: 53
              protocol: udp
            - target: 953
              published: 953
              protocol: tcp
              host_ip: 127.0.0.1
        volumes:
            - type: bind
              source: ./bind
              target: /etc/bind
              read_only: true
            - type: tmpfs
              target: /var/cache/bind
            - type: tmpfs
              target: /var/lib/bind
            - /var/log/bind:/var/log/bind
        restart: always

    dev:
        image: ghcr.io/shqld/dev/web:latest
        environment:
            - PORT=3000
        restart: always

    me:
        image: ghcr.io/shqld/me/web:latest
        environment:
            - PORT=3000
        restart: always
