version: '3.8'
services:
    www:
        image: ghcr.io/shqld/dev/web:latest
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
        networks:
            - system_default
        deploy:
            replicas: 1

    me:
        image: ghcr.io/shqld/me/web:latest
        ports:
            - "3001:3001"
        environment:
            - PORT=3001
        networks:
            - system_default
        deploy:
            replicas: 1

networks:
    system_default:
        external: true
