version: '3.8'
services:
    www:
        image: ghcr.io/shqld/dev/web:latest
        networks:
            - gateway
        user: '${CONTAINER_UID}'
        deploy:
            replicas: 1

networks:
    gateway:
        name: gateway
        external: true

        # update_config:
        #     parallelism: 2
        #     order: start-first
        #     failure_action: rollback
        # rollback_config:
        #     parallelism: 0
        #     order: stop-first
        # restart_policy:
        #     condition: any
        #     max_attempts: 3
        #     window: 120s
