version: '3.8'
services:
    www:
        image: ghcr.io/shqld/dev/web:latest
        ports:
            - "3000:3000"
        deploy:
            replicas: 1

    varnish:
        build: ./varnish
        ports:
            - "8080:6081"
        tmpfs: /var/lib/varnish:exec
        volumes:
            - /ops/app/varnish/src:/etc/varnish:ro
            - /var/log/varnish:/var/log/varnish
        deploy:
            replicas: 1
