version: '3'

tasks:
    setup:
        status:
            - docker-compose -f /ops/app/docker-compose.yaml ps | grep -q app_www
        cmds:
            - task: default

    default:
        deps:
            - docker-login
        cmds:
            - docker-compose -f /ops/app/docker-compose.yaml up -d

    restart:
        deps:
            - docker-login
        cmds:
            - docker-compose -f /ops/app/docker-compose.yaml restart

    logs:
        cmds:
            - docker-compose -f /ops/app/docker-compose.yaml logs

    docker-login:
        silent: true
        status:
            - grep -q 'ghcr.io' < "$HOME/.docker/config.json"
        cmds:
            - test -f "${DOCKER_REGISTRY_TOKEN}"
            - echo "${DOCKER_REGISTRY_TOKEN}" | docker login -u shqld --password-stdin ghcr.io
