version: '3'

tasks:
    setup:
        cmds:
            - task: up

    up:
        deps:
            - docker-login
        cmds:
            - docker stack up app -c /ops/app/docker-compose.yaml

    down:
        cmds:
            - docker stack down app -c /ops/app/docker-compose.yaml

    docker-login:
        silent: true
        status:
            - grep -q 'ghcr.io' < "$HOME/.docker/config.json"
        cmds:
            - test -n "${DOCKER_REGISTRY_TOKEN}"
            - echo "${DOCKER_REGISTRY_TOKEN}" | docker login -u shqld --password-stdin ghcr.io
