version: '3'

tasks:
    setup:
        cmds:
            - task: up

    up:
        deps:
            - docker-login
            - build
        cmds:
            - docker-compose -f /ops/app/docker-compose.yaml up -d

    build:
        sources:
            - /ops/app/varnish/Dockerfile
        cmds:
            - docker-compose -f /ops/app/docker-compose.yaml build

    down:
        cmds:
            - docker-compose -f /ops/app/docker-compose.yaml down

    restart:
        sources:
            - /ops/app/varnish/default.vcl
        # deps:
            # - docker-login
            # - up
        cmds:
            - docker-compose -f /ops/app/docker-compose.yaml restart

    update:
        deps:
            - docker-login
        cmds:
            - docker-compose -f /ops/app/docker-compose.yaml pull
            - task: restart

    logs:
        deps:
            - up
        cmds:
            - docker-compose -f /ops/app/docker-compose.yaml logs

    docker-login:
        silent: true
        status:
            - grep -q 'ghcr.io' < "$HOME/.docker/config.json"
        cmds:
            - test -n "${DOCKER_REGISTRY_TOKEN}"
            - echo "${DOCKER_REGISTRY_TOKEN}" | docker login -u shqld --password-stdin ghcr.io
