version: '3.8'
services:
    gateway:
        image: cdrocker/nginx:latest
        ports:
            - '443:443/tcp'
            - '443:443/udp'
        volumes:
            - /ops/daemon/gateway/nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        deploy:
            replicas: 1
        # update_config:
        #     parallelism: 2
        #     order: start-first
        #     failure_action: rollback
        # rollback_config:
        #     parallelism: 0
        #     order: stop-first
        # restart_policy:
        #     condition: any
        #     max_attempts: 3
        #     window: 120s
