version: '3.8'
services:
    nginx:
        image: ranadeeppolavarapu/nginx-http3
        tmpfs: /var/lib/varnish:exec
        volumes:
            - /ops/system/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt/live/shqld.dev/fullchain.pem:/etc/letsencrypt/live/shqld.dev/fullchain.pem:ro
            - /etc/letsencrypt/live/shqld.dev/privkey.pem:/etc/letsencrypt/live/shqld.dev/privkey.pem:ro
            - /etc/letsencrypt/live/me.shqld.dev/fullchain.pem:/etc/letsencrypt/live/me.shqld.dev/fullchain.pem:ro
            - /etc/letsencrypt/live/me.shqld.dev/privkey.pem:/etc/letsencrypt/live/me.shqld.dev/privkey.pem:ro
            - /var/log/nginx:/var/log/nginx
        deploy:
            replicas: 1
        network_mode: host

    varnish:
        build: ./varnish
        ports:
            - "8080:6081"
        networks:
            - app_default
        tmpfs: /var/lib/varnish:exec
        volumes:
            - /ops/system/varnish/default.vcl:/etc/varnish/default.vcl:ro
            - /var/log/varnish:/var/log/varnish
        deploy:
            replicas: 1

networks:
  app_default:
    external: true
