version: '3.8'
services:
    nginx:
        image: ranadeeppolavarapu/nginx-http3
        ports:
            - target: 443
              published: 443
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: udp
              mode: host
        depends_on:
            - varnish
        volumes:
            - type: bind
              source: /ops/system/nginx/nginx.conf
              target: /etc/nginx/nginx.conf
              read_only: true
            - type: bind
              source: /var/log/nginx
              target: /var/log/nginx
            - type: bind
              source: /etc/letsencrypt/live
              target: /etc/letsencrypt/live
              read_only: true
        deploy:
            replicas: 1

    varnish:
        image: ghcr.io/shqld/varnish:latest
        tmpfs: /var/lib/varnish:exec
        volumes:
            - type: bind
              source: /ops/system/varnish
              target: /etc/varnish
              read_only: true
            - type: bind
              source: /var/log/varnish
              target: /var/log/varnish
        deploy:
            replicas: 1
