version: '3.8'
services:
    nginx:
        image: ranadeeppolavarapu/nginx-http3
        ports:
            - target: 443
              published: 443
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: udp
              mode: host
        depends_on:
            - varnish
        volumes:
            - /ops/system/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /var/log/nginx:/var/log/nginx
            - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
        deploy:
            replicas: 1

    varnish:
        image: ghcr.io/shqld/varnish:latest
        tmpfs: /var/lib/varnish:exec
        volumes:
            - /ops/system/varnish:/etc/varnish:ro
            - /var/log/varnish:/var/log/varnish
        deploy:
            replicas: 1
