version: '3'

tasks:
    setup:
        cmds:
            - task: up

    up:
        cmds:
            - docker-compose -f /ops/system/docker-compose.yaml up -d --build

    down:
        cmds:
            - docker-compose -f /ops/system/docker-compose.yaml down

    restart:
        sources:
            - /ops/system/nginx/nginx.conf
            - /ops/system/varnish/default.vcl
        cmds:
            - docker-compose -f /ops/system/docker-compose.yaml restart

    logs:
        deps:
            - up
        cmds:
            - docker-compose -f /ops/system/docker-compose.yaml logs
