version: '3'

tasks:
    setup:
        cmds:
            - task: up

    up:
        cmds:
            - docker stack up system -c /ops/system/docker-compose.yaml

    down:
        cmds:
            - docker stack down system -c /ops/system/docker-compose.yaml
