version: '3'

tasks:
    default:
        deps:
            - sho
            - daemon
            - app

    sho:
        cmds:
            - task: sho_add_user
            - task: sho_add_user_to_group
            - task: sho_change_ownership_of_ops
            - task: sho_init_ssh
            - task: sho_init_sudoers

    daemon:
        cmds:
            - task: daemon_add_user

    app:
        cmds:
            - task: app_add_user

    sho_add_user:
        desc: Add user(sho)
        status:
            - id -u sho
        cmds:
            - useradd sho

    sho_add_user_to_group:
        desc: Add user(sho) to group(docker)
        deps:
            - sho_add_user
            # - :packages:docker
        status:
            - grep -q 'docker:.*:sho' -q < /etc/group
        cmds:
            - usermod -a -G docker sho

    sho_change_ownership_of_ops:
        desc: Set /ops owner to user&group(sho)"
        deps:
            - sho_add_user
        status:
            - ls -la / | grep ops | grep sho
        cmds:
            - chown sho -R /ops

    sho_init_ssh:
        desc: Set up ssh authorization for user(sho)
        deps:
            - sho_add_user
        status:
            - test -d /home/sho/.ssh
            - test -f /home/sho/.ssh/authorized_keys
        cmds:
            - mkdir -p /home/sho/.ssh
            - curl https://github.com/shqld.keys > /home/sho/.ssh/authorized_keys
            - chmod 600 /home/sho/.ssh/authorized_keys
            - chmod 700 /home/sho/.ssh
            - chown sho -R /home/sho/.ssh

    sho_init_sudoers:
        desc: Set up sudoers for user(sho)
        sources:
            - /ops/setup/users/sho/sudoers
        generates:
            - /etc/sudoers.d/sho
        cmds:
            - sh /ops/setup/users/sho/sudoers > /etc/sudoers.d/sho

    daemon_add_user:
        desc: Add user(daemon)
        status:
            - id -u daemon
        cmds:
            - useradd daemon

    app_add_user:
        desc: Add user(app)
        status:
            - id -u app
        cmds:
            - useradd app
