version: '3.8'
services:
    web:
        image: ghcr.io/shqld/dev/app:latest
        ports:
            - '3427:3000'
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
            rollback_config:
                parallelism: 0
                order: stop-first
            restart_policy:
                condition: any
                max_attempts: 3
                window: 120s
