.PHONY docker-login
docker-login:
	docker login "$@"

.PHONY docker-pull
docker-pull:
	docker pull "$@"

.PHONY docker-service-update
docker-service-update:
	docker service update "$@"

.PHONY docker-stack-up
docker-stack-up:
	docker stack up "$@"
