#!/bin/bash

set -eu

echo "(setup/init) Starting ..."

cd /ops

echo "Exporting constants as environment variables ..."
while read -r env ; do
  export ${env?}
done < setup/constants.env

setup/scripts/1_init_ops
setup/scripts/2_add_user
setup/scripts/3_install_deps
setup/scripts/5_init_user_menial
setup/scripts/6_setup_docker

rm -r setup

echo "(setup/init) Done"
