#!/bin/sh

set -eu

# -----------------------------------------------

/ops/users/sho/setup
/ops/users/robot/setup

/ops/setup/scripts/install_packages
/ops/setup/scripts/setup_docker
/ops/setup/scripts/setup_ipv6

echo "All setup is done"
