version: '3'

includes:
    packages: ./packages
    users: ./users

tasks:
    default:
        deps:
            - sshd
            - ipv6
            - deno
            - task: packages:default
            - task: users:default
    
    deno:
        desc: Install deno
        cmds:
            - curl -fsSL https://deno.land/install.sh | sh
            - ln -sfnv /root/.deno/bin/deno /usr/local/bin/deno
        status:
            - which deno

    sshd:
        silent: true
        cmds:
            - |
                cat << EOF >> /etc/ssh/sshd_config
                Match User *
                    PasswordAuthentication no
                    PubkeyAuthentication yes
                EOF
            - systemctl restart sshd
        status:
            - grep -q 'Match User \*' < /etc/ssh/sshd_config

    ipv6:
        status:
            - grep -q 'net.ipv6.conf.all.disable_ipv6 = 0' /etc/sysctl.conf
            - grep -q 'net.ipv6.conf.default.disable_ipv6 = 0' /etc/sysctl.conf
            - grep -q '^#IPV6' /etc/sysconfig/network && exit 1 || exit 0
            - grep -q '^#IPV6' /etc/sysconfig/network-scripts/ifcfg-ens3 && exit 1 || exit 0
        # https://manual.sakura.ad.jp/vps/network/ipv6/centos-stream-8.html
        cmds:
            - cat /etc/sysctl.conf
            - sed -i -e "/net.ipv6.conf.all.disable_ipv6/s/1/0/" /etc/sysctl.conf
            - sed -i -e "/net.ipv6.conf.default.disable_ipv6/s/1/0/" /etc/sysctl.conf
            - cat /etc/sysctl.conf
            - ip addr show ens3
            - cat /etc/sysconfig/network
            - cat /etc/sysconfig/network-scripts/ifcfg-ens3
            - sed -i -e "s/^#//g" /etc/sysconfig/network
            - sed -i -e "s/^#//g" /etc/sysconfig/network-scripts/ifcfg-ens3
            - cat /etc/sysconfig/network
            - cat /etc/sysconfig/network-scripts/ifcfg-ens3
