version: '3'

tasks:
    default:
        deps:
            - sshd
            - install_packages
            - docker
            - ipv6
        cmds:
            - reboot

    sshd:
        cmds:
            - |
                cat << EOF > /etc/ssh/sshd_config
                Match User *
                    PasswordAuthentication no
                    PubkeyAuthentication yes
                EOF
            - systemctl restart sshd
        status:
            - grep -q 'Match User *' < /etc/ssh/sshd_config

    install_packages:
        cmds:
            - /ops/setup/scripts/install_packages

    docker:
        cmds:
            - /ops/setup/scripts/setup_docker

    ipv6:
        cmds:
            - /ops/setup/scripts/setup_ipv6
