version: '3'

includes:
    users: ./users

tasks:
    default:
        deps:
            - sshd
            - packages
            - docker
            - docker-compose
            - ipv6
            - task: users:default

    sshd:
        silent: true
        cmds:
            - |
                cat << EOF > /etc/ssh/sshd_config
                Match User *
                    PasswordAuthentication no
                    PubkeyAuthentication yes
                EOF
            - systemctl restart sshd
        status:
            - grep -q 'Match User *' < /etc/ssh/sshd_config

    packages:
        sources:
            - /ops/setup/packages.txt
        cmds:
            - xargs dnf install -y < /ops/setup/packages.txt

    docker:
        status:
            - systemctl list-unit-files --state=enabled | grep -q docker.service
            - systemctl list-units --type=service --state=running | grep -q docker.service
        cmds:
            - yum install -y yum-utils
            - |
                yum-config-manager -y --add-repo \
                    https://download.docker.com/linux/centos/docker-ce.repo
            - yum -y remove podman # https://github.com/containers/podman/issues/4791
            - yum install -y docker-ce docker-ce-cli containerd.io
            - systemctl enable docker
            - systemctl start docker

    docker-compose:
        deps:
            - docker
        status:
            - which docker-compose
        cmds:
            - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
            - chmod +x /usr/bin/docker-compose

    ipv6:
        status:
            - grep -q 'net.ipv6.conf.all.disable_ipv6 = 0' /etc/sysctl.conf
            - grep -q 'net.ipv6.conf.default.disable_ipv6 = 0' /etc/sysctl.conf
            - grep -q '^#IPV6' /etc/sysconfig/network && exit 1 || exit 0
            - grep -q '^#IPV6' /etc/sysconfig/network-scripts/ifcfg-ens3 && exit 1 || exit 0
        # https://manual.sakura.ad.jp/vps/network/ipv6/centos-stream-8.html
        cmds:
            - cat /etc/sysctl.conf
            - sed -i -e "/net.ipv6.conf.all.disable_ipv6/s/1/0/" /etc/sysctl.conf
            - sed -i -e "/net.ipv6.conf.default.disable_ipv6/s/1/0/" /etc/sysctl.conf
            - cat /etc/sysctl.conf
            - ip addr show ens3
            - cat /etc/sysconfig/network
            - cat /etc/sysconfig/network-scripts/ifcfg-ens3
            - sed -i -e "s/^#//g" /etc/sysconfig/network
            - sed -i -e "s/^#//g" /etc/sysconfig/network-scripts/ifcfg-ens3
            - cat /etc/sysconfig/network
            - cat /etc/sysconfig/network-scripts/ifcfg-ens3
