version: '3'

tasks:
    default:
        deps:
            - sshd
            - packages
            - docker
            - ipv6
        cmds:
            - reboot

    sshd:
        cmds:
            - |
                cat << EOF > /etc/ssh/sshd_config
                Match User *
                    PasswordAuthentication no
                    PubkeyAuthentication yes
                EOF
            - systemctl restart sshd
        status:
            - grep -q 'Match User *' < /etc/ssh/sshd_config

    packages:
        sources:
            - /ops/setup/packages.txt
        cmds:
            - xargs dnf install -y < /ops/setup/packages.txt

    docker:
        status:
            - systemctl list-unit-files --state=enabled | grep -q docker.service
            - systemctl list-units --type=service --state=running | grep -q docker.service
        cmds:
            - yum install -y yum-utils
            - |
                yum-config-manager -y --add-repo \
                    https://download.docker.com/linux/centos/docker-ce.repo
            - yum -y remove podman # https://github.com/containers/podman/issues/4791
            - yum install -y docker-ce docker-ce-cli containerd.io
            - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            - chmod +x /usr/local/bin/docker-compose
            - systemctl enable docker
            - systemctl start docker

    ipv6:
        cmds:
            - /ops/setup/scripts/setup_ipv6
