version: '3.8'
services:
    web:
        image: ghcr.io/shqld/dev/web:latest
        ports:
            - '3000:3000'
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
            rollback_config:
                parallelism: 0
                order: stop-first
            restart_policy:
                condition: any
                max_attempts: 3
                window: 120s

    nginx:
        image: nginx:1.21.1-alpine
        ports:
            - '443:443'
        volumes:
            - /ops/src/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /ops/logs:/var/log
            - /etc/letsencrypt/live/shqld.dev:/etc/letsencrypt/live/shqld.dev
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
            rollback_config:
                parallelism: 0
                order: stop-first
            restart_policy:
                condition: any
                max_attempts: 3
                window: 120s
