name: Echo test
on:
    push:
        branches:
            - main

jobs:
    update-remote:
        runs-on: ubuntu-latest
        steps:
            - name: Update /ops
              uses: appleboy/ssh-action@master
              with:
                  host: shqld.dev
                  username: robot
                  key: ${{ secrets.ROBOT_PRIVATE_KEY }}
                  script: |
                      sudo rm -rf /ops \
                      && sudo git clone https://github.com/shqld/ops.git /ops --depth 1 \
                      && sudo task setup -d /ops --silent
